app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


//get('/', function()
//{
//    if (Auth::check()) return redirect('/');
//    return redirect('login');
//});
Route::get('/', 'QuestionPapersController@index');
//get('/', function()
//{
//    if (Auth::check()) return 'Welcome back, '  . Auth::user()->username;
//    return 'Hi guest. ' . link_to('login', 'Login With facebook!');
//});

Route::get('home', 'HomeController@index');
Route::get('login','AuthController@login');
Route::get('logout','AuthController@logout');

Route::post('data-filter',function()
            {
            $query = Input::get('q','');
            
            $question_query = App\QuestionPapers::Orderby( 'id', 'desc' );
            foreach($query as $key=>$value){
                if(!empty($value)|| $value!='')
                $question_query->whereIn($key,[$value]);
            }
            $question_papers = $question_query->get();

            return Response::json(view('qpapers.items',array('question_papers'=>$question_papers))->render);
            });

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

 Route::get('login/{provider?}', 'AuthController@login');

Route::bind('qp',function($id)
            {
                return App\QuestionPapers::where('id',$id)->first();
            });

$router->resource('qp','QuestionPapersController',['only' => [
	'create','store','destroy'
       ]]);

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	<link href="/css/app.css" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Laravel</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="/">Home</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="/auth/login">Login</a></li>
						<li><a href="/auth/register">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="/auth/logout">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/error.blade.php
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='http://fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
{!! HTML::style('css/error.css'); !!}
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{!! csrf_token() !!}" />
<link href='http://www.google.com/fonts#UsePlace:use/Collection:Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<title>VQ Papers</title>
{!! HTML::style(elixir("css/app/all.css")) !!}
{!! HTML::script(elixir("js/app/all.js")) !!}
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
    <body>
        <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
    {!! link_to_route('qp.create','Upload',null,['class'=>'btn btn-primary pull-right upload-button','multiple'=>'multiple']) !!}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">{!! HTML::image('images/Logo.png') !!}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
@if(!Auth::check())
<li><a href="login/facebook" class="btn btn-xs btn-facebook pull-right"><i class="fa fa-facebook"></i> | Connect with Facebook</a></li>
<li><a href="login/google" class="btn btn-xs btn-google-plus pull-right"><i class="fa fa-google-plus"></i> | Connect with Google</a> </li>
@endif
@if(Auth::check())
    <li>{!! Auth::user()->name !!}</li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <img src={!! Auth::user()->avatar !!} width=25 height=25 /> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="logout" > Logout </a></li>

              </ul>
            </li>
@endif
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
        <div class="container" id="middle-container" >
            @yield('content')
        </div>
    </body>
</html>