app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


//get('/', function()
//{
//    if (Auth::check()) return redirect('/');
//    return redirect('login');
//});
Route::get('/', 'QuestionPapersController@index');
//get('/', function()
//{
//    if (Auth::check()) return 'Welcome back, '  . Auth::user()->username;
//    return 'Hi guest. ' . link_to('login', 'Login With facebook!');
//});

Route::get('home', 'HomeController@index');
Route::get('login','AuthController@login');
Route::get('logout','AuthController@logout');

Route::post('data-filter',function()
            {
            $query = Input::get('q','');
            
            $question_query = App\QuestionPapers::Orderby( 'id', 'desc' );
            foreach($query as $key=>$value){
                if(!empty($value)|| $value!='')
                $question_query->whereIn($key,[$value]);
            }
            $question_papers = $question_query->get();

            return Response::json(view('qpapers.items',array('question_papers'=>$question_papers))->render);
            });

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

 Route::get('login/{provider?}', 'AuthController@login');

Route::bind('qp',function($id)
            {
                return App\QuestionPapers::where('id',$id)->first();
            });

$router->resource('qp','QuestionPapersController',['only' => [
	'create','store','destroy'
       ]]);

resources/views/qpapers/createqp.blade.php
@extends('master')

@section('content')
<!-- Latest compiled and minified CSS -->
{!! HTML::script('https://www.google.com/recaptcha/api.js'); !!}
 {!! HTML::style('css/custom.css'); !!}

<div class="row" id="createqp">
<div class="col-sm-10">
<h2 class="col-sm-10" id="uploadheader">Upload</h2>
  <div class="clearfix"></div>
{!! Form::open(['route'=>'qp.store','files'=>true,'class'=>"form-horizontal"]) !!}

<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
{!! Form::label('title','Title',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-6">
{!! Form::text('title',null,['class'=>'form-control']) !!}
    {!! $errors->first('title','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}">
{!! Form::label('type','Type',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-6">
{!! Form::select('type', array(''=>'--Select--','1'=>'Previous paper','2'=>'Model paper'),  null,['class'=>'form-control']) !!}
{!! $errors->first('qtype','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('year') ? 'has-error' : '' }}">
{!! Form::label('year','Year',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-6">
{!! Form::select('year', $years, null,['class'=>'form-control searchable']) !!}
{!! $errors->first('year','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('syllabas') ? 'has-error' : '' }}">
{!! Form::label('syllabas','Syllabas',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-6">
{!! Form::select('syllabas', array(''=>'--Select--') + $syllabas, null,['class'=>'form-control searchable']) !!}
{!! $errors->first('syllabas','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group">
{!! Form::label('class','Class',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-6">
{!! Form::select('class', array('--Select--') + $classes, null,['class'=>'form-control searchable']) !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('qpfile') ? 'has-error' : '' }}">
{!! Form::label('file','File',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-6">
{!! Form::file('qpfile',['class'=>'form-control']) !!}
{!! $errors->first('qpfile','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group">
<div class="col-sm-offset-2 col-sm-6">
{!! app('captcha')->display(); !!}
</div>
</div>
    
<div class="form-group">
<div class="col-sm-offset-2 col-sm-6">
{!! Form::submit('Upload',['class'=>'btn btn-primary'])  !!}
{!! link_to('/','Cancel',['class'=>'btn btn-default']) !!}
</div>
</div>
{!! Form::close() !!}
</div>
</div>
<script type="text/javascript">
  $('.searchable').select2({
   placeholder: "-- Select --",
allowClear: true
  });
</script>
@stop

resources/views/qpapers/index.blade.php
@extends('master')
@section('content')

 {!! HTML::style('css/custom.css'); !!}
  {!! HTML::style('css/social-buttons.css'); !!}

<div class="row col-sm-12">
     <div class="col-sm-3">
  {!! Form::select('year', array('Years') + $years, null,['id'=>'year','class'=>'form-control filterable','multiple'=>'multiple']) !!}
   </div>
  <div class="col-sm-3">
 {!! Form::select('type', array('1'=>'Previous paper','2'=>'Model paper'),  null,['id'=>'type','class'=>'form-control filterable','multiple'=>'multiple']) !!}
 </div>
     <div class="col-sm-3">
  {!! Form::select('syllabas', array('Syllabas') + $syllabas, null,['id'=>'syllabas','class'=>'form-control filterable','multiple'=>'multiple']) !!}
     </div>
       <div class="col-sm-3">
  {!! Form::select('class', array('Class') + $classes, null,['id'=>'class','class'=>'form-control filterable','multiple'=>'multiple']) !!}
       </div>
</div>
     
      @if(Session::has('notification'))
        <div class="alert alert-info">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
         <h4>{{ Session::get('notification') }}</h4>
        </div>
      @endif
         
 <div class="qpaperdata col-sm-12">
@include('/qpapers/items')
 </div>
  {!! HTML::script('js/filter.js') !!}
 @stop

resources/views/qpapers/items.blade.php
          <ul id="qplist" class="list-unstyled">
       
        @foreach ($question_papers as $question_paper)            
        <li>
        <div class="col-md-12" id="qpdata">
        <!--<div class="pull-left">-->
        <h3>{{ $question_paper->title }}{!! link_to_route('qp.destroy','',[$question_paper->id],['class'=>'pull-right rest-delete glyphicon glyphicon-remove pull-right','data-method'=>"DELETE" ,'csrf-token'=>"$token",'data-confirm'=>"Are you sure?"]) !!}</h3>
        <b>Uploaded at:</b> {{ $question_paper->created_at }}
            <b>Year:</b> {!! $question_paper->year !!}
            <b>Syllabas:</b> {!! get_resourcename('syllabas',$question_paper->syllabas) !!}
            <b>Class:</b> {!! get_resourcename('class',$question_paper->class) !!}
        <a href="{{ URL::to('https://s3-us-west-2.amazonaws.com/vqpapers/'. $question_paper->qpfile)  }}" id="download-paper" class="pull-right glyphicon">Download</a>   
        <!--</div> -->

        <!--{!! Form::open(['method'=>'DELETE', 'route'=>['qp.destroy',$question_paper->id]]) !!}-->
        <!--{!! Form::submit('Delete',['class' => 'btn btn-danger']) !!}-->
        <!--{!! Form::close() !!}-->

</div></li>
        @endforeach 
        </ul>
<script>restful.init($('.rest-delete'));</script>
  {!! $question_papers->appends(['q' => $q])->render(); !!}

resources/views/qpapers/update.blade.php
{!! Form::model($song,['route'=>['song_update_path',$song->slug],'method'=>'PATCH']) !!}
@extends('master')
@section('content')
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="/css/select2.min.css" />
<script src="/js/select2.full.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>
        
<h2>Upload Question Paper</h2>
{!! Form::model(['route'=>['update'],'files'=>true,'class'=>"form-horizontal"]) !!}

<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
{!! Form::label('title','Title',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-10">
{!! Form::text('title',null,['class'=>'form-control']) !!}
    {!! $errors->first('title','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('qtype') ? 'has-error' : '' }}">
{!! Form::label('qtype','Type',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-10">
{!! Form::select('qtype', array(''=>'--Select--','1'=>'Previous paper','2'=>'Model paper'),  null,['class'=>'form-control']) !!}
{!! $errors->first('qtype','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('year') ? 'has-error' : '' }}">
{!! Form::label('year','Year',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-10">
{!! Form::select('year', $years, null,['class'=>'form-control searchable']) !!}
{!! $errors->first('year','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('syllabas') ? 'has-error' : '' }}">
{!! Form::label('syllabas','Syllabas',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-10">
{!! Form::select('syllabas', array(''=>'--Select--') + $syllabas, null,['class'=>'form-control searchable']) !!}
{!! $errors->first('syllabas','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group">
{!! Form::label('class','Class',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-10">
{!! Form::select('class', array('--Select--') + $classes, null,['class'=>'form-control searchable']) !!}
</div>
</div>
    
<div class="form-group {{ $errors->has('qpfile') ? 'has-error' : '' }}">
{!! Form::label('file','File',['class'=>"col-sm-2 control-label"]) !!}
<div class="col-sm-10">
{!! Form::file('qpfile',['class'=>'form-control']) !!}
{!! $errors->first('qpfile','<span class="help-block">:message</span>') !!}
</div>
</div>
    
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<div class="g-recaptcha" data-sitekey="6LfugwATAAAAAOuuuTsC98pXb64OOIW-Mcf-PghZ"></div>
</div>
</div>
    
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
{!! Form::submit('Upload',['class'=>'btn btn-primary'])  !!}
{!! link_to_route('qp.index','Cancel',null,['class'=>'btn btn-default']) !!}
</div>
</div>
{!! Form::close() !!}

<script type="text/javascript">
  $('.searchable').select2({
   placeholder: "-- Select --",
allowClear: true
  });
</script>
@stop